<?php

/**
 * Default error page.
 */

namespace Nette\Diagnostics;

?>
<!DOCTYPE html><!-- "' --></script></style></pre></xmp></table>
<html>
<head>
	<meta charset="utf-8">
	<meta name="author" content="PeckaDesign (www.peckadesign.cz)">
	<meta name="keywords" content="">
	<meta name="description" content="">

	<meta name="HandheldFriendly" content="True">
	<meta name="MobileOptimized" content="320">
	<meta name="viewport" content="width=device-width; initial-scale=1.0; minimum-scale=1.0; maximum-scale=1.0; user-scalable=0;">

	<title>Údržba serveru - Megapixel</title>

	<link rel="Shortcut icon" href="/favicon.ico" type="image/x-icon">
	<link class="error500" rel="Stylesheet" href="/css/css500.css" media="screen, projection">
</head>
<body>
	<div id="pd-overlay">
		<div id="main500">
			<div class="content">
			<p id="logo">
				<img src="/img/logo-megapixel.png" alt="Megapixel" width="160" height="91" />
			</p>

			<p>
				Omlouváme se, probíhá údržba.<br>
				Prosím zkuste navštívit náš web za několik minut.<br><br>

				Děkujeme za pochopení.
			</p>
			</div>
			<p class="img">
				<img src="/img/illust/page-404.jpg" width="352" height="253" alt="404" class="right" />
			</p>
			<div class="break"></div>
		</div>
	</div>

<script type="text/javascript">/*<![CDATA[*/var bs=document.getElementById("pd-overlay");document.body.appendChild(bs);
for(var i=0,styles=document.styleSheets;i<styles.length;i++)"error500"!==(styles[i].owningElement||styles[i].ownerNode).className?(styles[i].oldDisabled=styles[i].disabled,styles[i].disabled=!0):styles[i].addRule?styles[i].addRule(".nette-collapsed","display: none"):styles[i].insertRule(".nette-collapsed { display: none }",0);
bs.onclick=function(b){for(var b=b||window.event,a=b.target||b.srcElement;a&&a.tagName&&"a"!==a.tagName.toLowerCase();)a=a.parentNode;if(!a||!a.rel)return!0;for(var d=a.getElementsByTagName("abbr")[0],c="next"===a.rel?a.nextSibling:document.getElementById(a.rel);1!==c.nodeType;)c=c.nextSibling;b=c.currentStyle?"none"==c.currentStyle.display:"none"==getComputedStyle(c,null).display;try{d.innerHTML=String.fromCharCode(b?9660:9658)}catch(e){}c.style.display=b?"code"===c.tagName.toLowerCase()?"inline":
"block":"none";if("netteBluescreenIcon"===a.id){a=0;for(d=document.styleSheets;a<d.length;a++)if("nette"!==(d[a].owningElement||d[a].ownerNode).className)d[a].disabled=b?!0:d[a].oldDisabled}return!1};/*]]>*/</script>

<script type="text/javascript" src="/js/analytics.js"></script>
<script type="text/javascript" src="/js/ga-atribuce.js?v=3"></script>

<script type="text/javascript">
	_ga.create('UA-830330-1', '.megapixel.cz');
	atribuceKampani.orderAfterInit();
	_gaq.push(['_trackPageview']);

	ga('create', 'UA-830330-3', {
		'cookieDomain': '.megapixel.cz'
	});
	ga('send', 'pageview');
</script>

</body>
</html>


